#!/usr/bin/env python3
"""
Generate a comprehensive music styles database for Style Mixer implementations.
This script creates a TypeScript file with all music genres, sub-genres, characteristics,
influences, eras, vocal styles, and production techniques.

Usage:
    python generate_music_styles.py --output path/to/musicStyles.ts
"""

import json
import argparse
from pathlib import Path
from typing import Dict, List

MUSIC_STYLES_DATA = {
    "genres": [
        "Rock", "Pop", "Jazz", "Blues", "Classical", "Electronic", "Hip-Hop",
        "Country", "Folk", "Soul", "Funk", "Reggae", "Metal", "Punk",
        "R&B", "Indie", "Alternative", "Synthwave", "Cyberpunk", "Ambient",
        "Techno", "House", "Trance", "Drum and Bass", "Dubstep", "Trap",
        "Lo-Fi", "Vaporwave", "Darkwave", "Industrial", "Experimental",
        "Psychedelic", "Prog Rock", "Grunge", "Britpop", "Emo", "Screamo",
        "Metalcore", "Deathcore", "Symphonic Metal", "Power Metal", "Thrash Metal",
        "Death Metal", "Black Metal", "Doom Metal", "Stoner Metal", "Sludge Metal",
        "EDM", "Chillwave", "Synthpop"
    ],
    "characteristics": {
        "Mood": [
            "Dark", "Melancholic", "Energetic", "Uplifting", "Aggressive",
            "Peaceful", "Mysterious", "Romantic", "Playful", "Sophisticated",
            "Ethereal", "Intense", "Moody", "Euphoric", "Introspective"
        ],
        "Texture": [
            "Atmospheric", "Dense", "Sparse", "Layered", "Minimalist",
            "Orchestral", "Organic", "Synthetic", "Raw", "Polished",
            "Gritty", "Smooth", "Chaotic", "Structured", "Ambient"
        ],
        "Production": [
            "Heavy Synth", "Analog Warmth", "Digital Precision", "Lo-Fi Quality",
            "Hi-Fi Clarity", "Distorted", "Clean", "Reverb-Heavy", "Dry",
            "Compressed", "Dynamic", "Layered", "Minimalist", "Maximalist", "Glitchy"
        ],
        "Energy": [
            "Low", "Medium", "High", "Explosive", "Subtle",
            "Building", "Constant", "Fluctuating", "Pulsing", "Static"
        ],
        "Complexity": [
            "Simple", "Moderate", "Complex", "Intricate", "Straightforward",
            "Experimental", "Accessible", "Avant-Garde", "Progressive", "Primitive"
        ],
        "Dynamics": [
            "Quiet", "Loud", "Balanced", "Dynamic Range", "Compressed",
            "Punchy", "Soft", "Aggressive", "Gentle", "Explosive"
        ]
    },
    "influences": [
        "Beatles", "Led Zeppelin", "Pink Floyd", "David Bowie", "Queen",
        "Miles Davis", "John Coltrane", "Billie Holiday", "Louis Armstrong", "Duke Ellington",
        "Bach", "Mozart", "Beethoven", "Chopin", "Wagner",
        "Bob Dylan", "Jimi Hendrix", "Eric Clapton", "Carlos Santana", "Prince",
        "Michael Jackson", "Aretha Franklin", "Marvin Gaye", "Stevie Wonder", "Al Green",
        "Kraftwerk", "Daft Punk", "Aphex Twin", "Autechre", "Warp Records",
        "Radiohead", "Nirvana", "The Cure", "Joy Division", "Depeche Mode",
        "Vangelis", "Tangerine Dream", "Jean-Michel Jarre", "Wendy Carlos", "Amon Düül II",
        "Kendrick Lamar", "Jay-Z", "Nas", "Tupac", "Biggie",
        "Björk", "Thom Yorke", "Grimes", "FKA twigs", "James Blake",
        "Burial", "Four Tet", "Boards of Canada", "Arca", "Oneohtrix Point Never"
    ],
    "eras": [
        "1920s", "1930s", "1940s", "1950s", "1960s",
        "1970s", "1980s", "1990s", "2000s", "2010s", "2020s"
    ],
    "vocal_styles": [
        "Operatic", "Smooth", "Raspy", "Powerful", "Whispered",
        "Robotic", "Ethereal", "Gritty", "Soulful", "Falsetto",
        "Growl", "Scream", "Spoken Word", "Sung", "Chanted",
        "Layered", "Isolated", "Harmonized", "Distorted", "Processed",
        "Breathy", "Nasal", "Deep", "High-Pitched", "Androgynous"
    ],
    "production_techniques": [
        "Layering", "Reverb", "Delay", "Distortion", "Compression",
        "EQ", "Sampling", "Looping", "Chopping", "Pitching",
        "Time-Stretching", "Filtering", "Modulation", "Automation", "Mixing",
        "Mastering", "Overdubbing", "Double-Tracking", "Panning", "Stereo Widening",
        "Sidechain", "Gating", "Limiting", "Expansion", "Saturation",
        "Convolution", "Granulation", "Synthesis", "Sequencing", "Quantization"
    ]
}

def generate_typescript(data: Dict) -> str:
    """Generate TypeScript code for music styles."""
    
    ts_code = '''// Auto-generated music styles database
// Generated by: generate_music_styles.py

export const MUSIC_GENRES = [
'''
    
    for genre in data["genres"]:
        ts_code += f'  "{genre}",\n'
    
    ts_code += '] as const;\n\n'
    
    # Add characteristics
    ts_code += 'export const MUSICAL_CHARACTERISTICS = {\n'
    for category, values in data["characteristics"].items():
        ts_code += f'  {category}: [\n'
        for value in values:
            ts_code += f'    "{value}",\n'
        ts_code += '  ] as const,\n'
    ts_code += '} as const;\n\n'
    
    # Add influences
    ts_code += 'export const INFLUENCES = [\n'
    for influence in data["influences"]:
        ts_code += f'  "{influence}",\n'
    ts_code += '] as const;\n\n'
    
    # Add eras
    ts_code += 'export const ERAS = [\n'
    for era in data["eras"]:
        ts_code += f'  "{era}",\n'
    ts_code += '] as const;\n\n'
    
    # Add vocal styles
    ts_code += 'export const VOCAL_STYLES = [\n'
    for style in data["vocal_styles"]:
        ts_code += f'  "{style}",\n'
    ts_code += '] as const;\n\n'
    
    # Add production techniques
    ts_code += 'export const PRODUCTION_TECHNIQUES = [\n'
    for technique in data["production_techniques"]:
        ts_code += f'  "{technique}",\n'
    ts_code += '] as const;\n'
    
    return ts_code

def main():
    parser = argparse.ArgumentParser(description="Generate music styles database")
    parser.add_argument("--output", type=str, default="musicStyles.ts",
                       help="Output file path (default: musicStyles.ts)")
    args = parser.parse_args()
    
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    ts_code = generate_typescript(MUSIC_STYLES_DATA)
    
    with open(output_path, "w") as f:
        f.write(ts_code)
    
    print(f"✅ Generated music styles database: {output_path}")
    print(f"   - {len(MUSIC_STYLES_DATA['genres'])} genres")
    print(f"   - {sum(len(v) for v in MUSIC_STYLES_DATA['characteristics'].values())} characteristics")
    print(f"   - {len(MUSIC_STYLES_DATA['influences'])} influences")
    print(f"   - {len(MUSIC_STYLES_DATA['eras'])} eras")
    print(f"   - {len(MUSIC_STYLES_DATA['vocal_styles'])} vocal styles")
    print(f"   - {len(MUSIC_STYLES_DATA['production_techniques'])} production techniques")

if __name__ == "__main__":
    main()
