import { PDFDocument, rgb, StandardFonts } from "pdf-lib";
import { nanoid } from "nanoid";
import type { Generation, Export } from "../drizzle/schema";

/**
 * Generate a unique share token for exports
 */
export function generateShareToken(): string {
  return nanoid(32);
}

/**
 * Export generation as PDF with metadata
 */
export async function generatePDF(generation: Generation): Promise<Buffer> {
  const pdfDoc = await PDFDocument.create();
  let currentPage = pdfDoc.addPage([612, 792]); // Letter size
  const { width, height } = currentPage.getSize();

  const timesRomanFont = await pdfDoc.embedFont(StandardFonts.TimesRoman);
  const timesRomanBoldFont = await pdfDoc.embedFont(StandardFonts.TimesRomanBold);
  const courierFont = await pdfDoc.embedFont(StandardFonts.Courier);

  let yPosition = height - 50;

  // Title
  currentPage.drawText(generation.title || "SunoForge Export", {
    x: 50,
    y: yPosition,
    size: 24,
    font: timesRomanBoldFont,
    color: rgb(0.2, 0.2, 0.2),
  });
  yPosition -= 40;

  // Metadata
  const metadata = generation.metadata as Record<string, unknown> || {};
  const metaText = `Type: ${generation.type} | Created: ${new Date(generation.createdAt).toLocaleDateString()}`;
  currentPage.drawText(metaText, {
    x: 50,
    y: yPosition,
    size: 10,
    font: timesRomanFont,
    color: rgb(0.5, 0.5, 0.5),
  });
  yPosition -= 30;

  // Separator
  currentPage.drawLine({
    start: { x: 50, y: yPosition },
    end: { x: width - 50, y: yPosition },
    thickness: 1,
    color: rgb(0.8, 0.8, 0.8),
  });
  yPosition -= 20;

  // Content
  const content = generation.content || "";
  const lines = content.split("\n");
  const maxCharsPerLine = 80;

  for (const line of lines) {
    // Wrap long lines
    const wrappedLines = line.length > maxCharsPerLine
      ? line.match(new RegExp(`.{1,${maxCharsPerLine}}`, "g")) || []
      : [line];

    for (const wrappedLine of wrappedLines) {
      if (yPosition < 50) {
        // Add new page if needed
        currentPage = pdfDoc.addPage([612, 792]);
        yPosition = height - 50;
      }

      currentPage.drawText(wrappedLine, {
        x: 50,
        y: yPosition,
        size: 11,
        font: courierFont,
        color: rgb(0.2, 0.2, 0.2),
      });
      yPosition -= 15;
    }
  }

  // Footer
  yPosition = 30;
  currentPage.drawText("Generated by SunoForge • https://sunoforge.app", {
    x: 50,
    y: yPosition,
    size: 8,
    font: timesRomanFont,
    color: rgb(0.7, 0.7, 0.7),
  });

  const pdfBytes = await pdfDoc.save();
  return Buffer.from(pdfBytes);
}

/**
 * Export generation as MIDI (simplified structure-based)
 * Creates a MIDI file based on the lyrics/prompt structure
 */
export function generateMIDI(generation: Generation): Buffer {
  // MIDI header
  const header = Buffer.from([
    0x4d, 0x54, 0x68, 0x64, // "MThd"
    0x00, 0x00, 0x00, 0x06, // Header length
    0x00, 0x00, // Format type 0
    0x00, 0x01, // Number of tracks
    0x00, 0x60, // Division (96 ticks per quarter note)
  ]);

  // Track header
  const trackHeader = Buffer.from([
    0x4d, 0x54, 0x72, 0x6b, // "MTrk"
  ]);

  // Track data
  const trackData: number[] = [];

  // Set tempo (120 BPM = 500000 microseconds per beat)
  trackData.push(0x00, 0xff, 0x51, 0x03, 0x07, 0xa1, 0x20);

  // Add notes based on content structure
  const content = generation.content || "";
  const lines = content.split("\n");
  let noteNumber = 60; // Middle C

  for (const line of lines) {
    if (line.includes("[")) {
      // Meta tag - change note
      noteNumber = Math.min(noteNumber + 2, 84);
    }

    // Note on
    trackData.push(0x00, 0x90, noteNumber, 0x64);
    // Note duration (quarter note)
    trackData.push(0x60);
    // Note off
    trackData.push(0x80, noteNumber, 0x40);
  }

  // End of track
  trackData.push(0x00, 0xff, 0x2f, 0x00);

  const trackDataBuffer = Buffer.from(trackData);
  const trackLength = trackDataBuffer.length;
  const trackLengthBuffer = Buffer.from([
    (trackLength >> 24) & 0xff,
    (trackLength >> 16) & 0xff,
    (trackLength >> 8) & 0xff,
    trackLength & 0xff,
  ]);

  return Buffer.concat([header, trackHeader, trackLengthBuffer, trackDataBuffer]);
}

/**
 * Export generation as JSON with full metadata
 */
export function generateJSON(generation: Generation): Buffer {
  const exportData = {
    version: "1.0.0",
    exportedAt: new Date().toISOString(),
    generation: {
      id: generation.id,
      type: generation.type,
      title: generation.title,
      content: generation.content,
      metadata: generation.metadata,
      imageUrl: generation.imageUrl,
      isFavorite: generation.isFavorite,
      isPublic: generation.isPublic,
      createdAt: generation.createdAt,
      updatedAt: generation.updatedAt,
    },
  };

  return Buffer.from(JSON.stringify(exportData, null, 2), "utf-8");
}

/**
 * Generate embed code for websites
 */
export function generateEmbedCode(shareToken: string, generationTitle: string): string {
  const embedUrl = `https://sunoforge.app/embed/${shareToken}`;
  return `<iframe src="${embedUrl}" width="100%" height="600" frameborder="0" allow="autoplay" title="${generationTitle}"></iframe>`;
}

/**
 * Generate short URL for sharing
 */
export function generateShareURL(shareToken: string, baseUrl: string = "https://sunoforge.app"): string {
  return `${baseUrl}/share/${shareToken}`;
}

/**
 * Parse MIDI structure from lyrics content
 */
export function parseLyricsStructure(content: string): {
  sections: Array<{ name: string; lines: number }>;
  totalLines: number;
} {
  const lines = content.split("\n");
  const sections: Array<{ name: string; lines: number }> = [];
  let currentSection = { name: "Intro", lines: 0 };

  for (const line of lines) {
    if (line.includes("[")) {
      if (currentSection.lines > 0) {
        sections.push(currentSection);
      }
      const match = line.match(/\[(.*?)\]/);
      currentSection = { name: match?.[1] || "Section", lines: 0 };
    } else if (line.trim()) {
      currentSection.lines++;
    }
  }

  if (currentSection.lines > 0) {
    sections.push(currentSection);
  }

  return {
    sections,
    totalLines: lines.length,
  };
}
